# Generated by Django 4.2.1 on 2023-06-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
