# Generated by Django 4.2.3 on 2023-07-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_turma_alunos_alter_turma_instrutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='aceitando_matriculas',
            field=models.BooleanField(default=True),
        ),
    ]
