# Generated by Django 4.2 on 2023-04-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pergunta',
            table='tb_perguntas',
        ),
    ]
