# Generated by Django 4.2.1 on 2023-06-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria', models.FloatField()),
                ('preco', models.FloatField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'tb_cursos',
            },
        ),
    ]
