"""Adicionado atributo data_hora na model postagem

Revision ID: 001c994f0021
Revises: 
Create Date: 2023-04-30 15:11:25.496771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001c994f0021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_postagens', sa.Column('data_hora', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_postagens', 'data_hora')
    # ### end Alembic commands ###
